/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login
         * @description Authenticate with email + password and return a session cookie.
         *
         *     On success: creates a server-side session row and sets the ``HttpOnly``
         *     session cookie.  Returns the public user object.
         *
         *     On failure: returns 401 (email not found or wrong password).  The same
         *     error is returned for both cases to prevent user-enumeration attacks.
         */
        post: operations["login_api_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Logout
         * @description Revoke the current session and clear the cookie.
         *
         *     Idempotent: if the cookie is absent or the session is already gone, the
         *     endpoint still returns 200 and clears the cookie.
         */
        post: operations["logout_api_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Me
         * @description Return the currently authenticated user.
         *
         *     Requires a valid session cookie.  Returns 401 if absent / expired.
         */
        get: operations["me_api_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/setup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Setup
         * @description Create the first admin user (first-run onboarding).
         *
         *     Self-closing and concurrency-safe: the admin user and a sentinel row
         *     (``app_config.key = 'onboarding_completed'``) are created in a **single
         *     transaction**.  Because ``app_config.key`` is the primary key, a second
         *     concurrent request that also passes the fast-path pre-check will hit a
         *     primary-key ``IntegrityError`` when it tries to insert the same sentinel,
         *     causing its transaction to roll back → 409.
         *
         *     This works even when two concurrent requests each read ``count == 0`` with
         *     *different* emails (which would bypass the email-unique constraint alone):
         *     only one can win the sentinel insert; the loser always gets 409.
         *
         *     Fast-path pre-check (sentinel exists or any user exists → 409) is kept for
         *     the common case, but the correctness guarantee comes from the unique-key
         *     sentinel insert, not from the pre-check.
         *
         *     On success returns the created user (HTTP 201).  Does NOT auto-login —
         *     the frontend transitions to the normal login screen after setup.
         */
        post: operations["setup_api_auth_setup_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/setup-status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Setup Status
         * @description Return whether first-run setup is still required.
         *
         *     ``setup_required: true``  — no users exist; the setup page must be shown.
         *     ``setup_required: false`` — at least one user exists; show the login page.
         *
         *     Unauthenticated — the frontend calls this on every load to decide which
         *     page to show before the user has any session cookie.
         */
        get: operations["setup_status_api_auth_setup_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Categories
         * @description Return a flat list of categories, optionally filtered.
         *
         *     - ``q``: case-insensitive substring match on the name.
         *     - ``parent_id``: when provided, return only categories with that parent.
         */
        get: operations["list_categories_api_categories_get"];
        put?: never;
        /**
         * Create Category
         * @description Create a new category.
         */
        post: operations["create_category_api_categories_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/categories/tree": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Tree
         * @description Return the full category tree as a nested structure.
         */
        get: operations["get_tree_api_categories_tree_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/categories/{category_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Category
         * @description Return a single category by id.
         */
        get: operations["get_category_api_categories__category_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete Category
         * @description Delete a category.
         *
         *     Returns 409 if the category still has child categories.
         */
        delete: operations["delete_category_api_categories__category_id__delete"];
        options?: never;
        head?: never;
        /**
         * Update Category
         * @description Partially update a category.
         *
         *     Reparenting (changing ``parent_id``) is cycle-checked in the service layer.
         */
        patch: operations["update_category_api_categories__category_id__patch"];
        trace?: never;
    };
    "/api/definitions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Definitions
         * @description Return a flat list of item definitions, optionally filtered.
         *
         *     - ``q``: case-insensitive substring match on the name.
         *     - ``category_id``: when provided, return only definitions with that category.
         */
        get: operations["list_definitions_api_definitions_get"];
        put?: never;
        /**
         * Create Definition
         * @description Create a new item definition.
         *
         *     If ``kind_id`` is omitted, the ``durable`` kind is used automatically.
         *     Returns 422 if ``kind_id`` is provided but does not exist.
         */
        post: operations["create_definition_api_definitions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/definitions/{definition_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Definition
         * @description Return a single item definition by id.
         */
        get: operations["get_definition_api_definitions__definition_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete Definition
         * @description Delete an item definition.
         */
        delete: operations["delete_definition_api_definitions__definition_id__delete"];
        options?: never;
        head?: never;
        /**
         * Update Definition
         * @description Partially update an item definition.
         *
         *     Returns 422 if ``kind_id`` is provided but does not exist.
         */
        patch: operations["update_definition_api_definitions__definition_id__patch"];
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Return service health.
         *
         *     ``status``      always ``"ok"`` while the process is running.
         *     ``version``     application release version.
         *     ``api_version`` integer compatibility number from Settings.
         *     ``db``          ``"ok"`` if ``SELECT 1`` succeeds; propagates exception
         *                     on DB failure (FastAPI returns 500).
         */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/instances": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Instances
         * @description Return a flat list of stock instances, optionally filtered.
         */
        get: operations["list_instances_api_instances_get"];
        put?: never;
        /**
         * Create Instance
         * @description Create a new stock instance.
         *
         *     Returns 422 if a serial is provided with quantity != 1.
         *     Returns 404 if definition_id or location_id does not exist.
         */
        post: operations["create_instance_api_instances_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/instances/{instance_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Instance
         * @description Return a single stock instance by id.
         */
        get: operations["get_instance_api_instances__instance_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete Instance
         * @description Delete a stock instance.
         */
        delete: operations["delete_instance_api_instances__instance_id__delete"];
        options?: never;
        head?: never;
        /**
         * Update Instance
         * @description Partially update a stock instance.
         *
         *     Returns 422 if the update would result in a serial with quantity != 1.
         */
        patch: operations["update_instance_api_instances__instance_id__patch"];
        trace?: never;
    };
    "/api/kinds": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Kinds
         * @description Return all item kinds (seeded: durable / consumable / perishable).
         *
         *     This endpoint is read-only — there are no write endpoints for kinds in M1.
         */
        get: operations["list_kinds_api_kinds_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/locations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Locations
         * @description Return a flat list of locations, optionally filtered.
         *
         *     - ``q``: case-insensitive substring match on the name.
         *     - ``parent_id``: when provided, return only locations with that parent.
         */
        get: operations["list_locations_api_locations_get"];
        put?: never;
        /**
         * Create Location
         * @description Create a new location.
         */
        post: operations["create_location_api_locations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/locations/tree": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Tree
         * @description Return the full location tree as a nested structure.
         */
        get: operations["get_tree_api_locations_tree_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/locations/{location_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Location
         * @description Return a single location by id.
         */
        get: operations["get_location_api_locations__location_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete Location
         * @description Delete a location.
         *
         *     Returns 409 if the location still has child locations.
         */
        delete: operations["delete_location_api_locations__location_id__delete"];
        options?: never;
        head?: never;
        /**
         * Update Location
         * @description Partially update a location.
         *
         *     Reparenting (changing ``parent_id``) is cycle-checked in the service layer.
         */
        patch: operations["update_location_api_locations__location_id__patch"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * CategoryCreate
         * @description Body for POST /categories.
         */
        CategoryCreate: {
            /** Description */
            description?: string | null;
            /** Name */
            name: string;
            /** Parent Id */
            parent_id?: number | null;
        };
        /**
         * CategoryResponse
         * @description Public representation of a Category (flat, no children).
         */
        CategoryResponse: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Description */
            description: string | null;
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Parent Id */
            parent_id: number | null;
        };
        /**
         * CategoryTreeNode
         * @description Recursive tree node for GET /categories/tree.
         */
        CategoryTreeNode: {
            /**
             * Children
             * @default []
             */
            children: components["schemas"]["CategoryTreeNode"][];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Description */
            description: string | null;
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Parent Id */
            parent_id: number | null;
        };
        /**
         * CategoryUpdate
         * @description Body for PATCH /categories/{id} — all fields optional.
         */
        CategoryUpdate: {
            /** Description */
            description?: string | null;
            /** Name */
            name?: string | null;
            /** Parent Id */
            parent_id?: number | null;
        };
        /**
         * DefinitionCreate
         * @description Body for POST /definitions.
         */
        DefinitionCreate: {
            /** Category Id */
            category_id?: number | null;
            /** Default Location Id */
            default_location_id?: number | null;
            /** Description */
            description?: string | null;
            /** Kind Id */
            kind_id?: number | null;
            /** Name */
            name: string;
            /**
             * Unit
             * @default pcs
             */
            unit: string;
        };
        /**
         * DefinitionResponse
         * @description Public representation of an ItemDefinition.
         */
        DefinitionResponse: {
            /** Category Id */
            category_id: number | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Default Location Id */
            default_location_id: number | null;
            /** Description */
            description: string | null;
            /** Id */
            id: number;
            kind: components["schemas"]["KindResponse"];
            /** Kind Id */
            kind_id: number;
            /** Name */
            name: string;
            /** Unit */
            unit: string;
        };
        /**
         * DefinitionUpdate
         * @description Body for PATCH /definitions/{id} — all fields optional.
         */
        DefinitionUpdate: {
            /** Category Id */
            category_id?: number | null;
            /** Default Location Id */
            default_location_id?: number | null;
            /** Description */
            description?: string | null;
            /** Kind Id */
            kind_id?: number | null;
            /** Name */
            name?: string | null;
            /** Unit */
            unit?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HealthResponse
         * @description Shape of the /health response (Step 3+).
         */
        HealthResponse: {
            /** Api Version */
            api_version: number;
            /** Db */
            db: string;
            /** Status */
            status: string;
            /** Version */
            version: string;
        };
        /**
         * InstanceCreate
         * @description Body for POST /instances.
         */
        InstanceCreate: {
            /** Definition Id */
            definition_id: number;
            /** Location Id */
            location_id?: number | null;
            /** Manufacturer */
            manufacturer?: string | null;
            /** Model Number */
            model_number?: string | null;
            /** Purchase Date */
            purchase_date?: string | null;
            /** Purchase Price */
            purchase_price?: number | string | null;
            /** Purchase Source */
            purchase_source?: string | null;
            /** Quantity */
            quantity?: number | string | null;
            /** Serial */
            serial?: string | null;
            /** Warranty Details */
            warranty_details?: string | null;
            /** Warranty Expires */
            warranty_expires?: string | null;
        };
        /**
         * InstanceResponse
         * @description Public representation of a StockInstance.
         */
        InstanceResponse: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Definition Id */
            definition_id: number;
            /** Id */
            id: number;
            /** Location Id */
            location_id: number | null;
            /** Manufacturer */
            manufacturer: string | null;
            /** Model Number */
            model_number: string | null;
            /** Purchase Date */
            purchase_date: string | null;
            /** Purchase Price */
            purchase_price: string | null;
            /** Purchase Source */
            purchase_source: string | null;
            /** Quantity */
            quantity: string;
            /** Serial */
            serial: string | null;
            /** Warranty Details */
            warranty_details: string | null;
            /** Warranty Expires */
            warranty_expires: string | null;
        };
        /**
         * InstanceUpdate
         * @description Body for PATCH /instances/{id} — all fields optional.
         */
        InstanceUpdate: {
            /** Location Id */
            location_id?: number | null;
            /** Manufacturer */
            manufacturer?: string | null;
            /** Model Number */
            model_number?: string | null;
            /** Purchase Date */
            purchase_date?: string | null;
            /** Purchase Price */
            purchase_price?: number | string | null;
            /** Purchase Source */
            purchase_source?: string | null;
            /** Quantity */
            quantity?: number | string | null;
            /** Serial */
            serial?: string | null;
            /** Warranty Details */
            warranty_details?: string | null;
            /** Warranty Expires */
            warranty_expires?: string | null;
        };
        /**
         * KindResponse
         * @description Public representation of an ItemKind.
         */
        KindResponse: {
            /** Code */
            code: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Id */
            id: number;
            /** Is System */
            is_system: boolean;
            /** Name */
            name: string;
        };
        /**
         * LocationCreate
         * @description Body for POST /locations.
         */
        LocationCreate: {
            /** Description */
            description?: string | null;
            /** Name */
            name: string;
            /** Parent Id */
            parent_id?: number | null;
        };
        /**
         * LocationResponse
         * @description Public representation of a Location (flat, no children).
         */
        LocationResponse: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Description */
            description: string | null;
            /** Id */
            id: number;
            /** Item Instance Id */
            item_instance_id: number | null;
            /** Name */
            name: string;
            /** Parent Id */
            parent_id: number | null;
        };
        /**
         * LocationTreeNode
         * @description Recursive tree node for GET /locations/tree.
         */
        LocationTreeNode: {
            /**
             * Children
             * @default []
             */
            children: components["schemas"]["LocationTreeNode"][];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Description */
            description: string | null;
            /** Id */
            id: number;
            /** Item Instance Id */
            item_instance_id: number | null;
            /** Name */
            name: string;
            /** Parent Id */
            parent_id: number | null;
        };
        /**
         * LocationUpdate
         * @description Body for PATCH /locations/{id} — all fields optional.
         */
        LocationUpdate: {
            /** Description */
            description?: string | null;
            /** Item Instance Id */
            item_instance_id?: number | null;
            /** Name */
            name?: string | null;
            /** Parent Id */
            parent_id?: number | null;
        };
        /**
         * LoginRequest
         * @description Body for POST /auth/login.
         */
        LoginRequest: {
            /** Email */
            email: string;
            /** Password */
            password: string;
        };
        /**
         * MeResponse
         * @description Response body for GET /auth/me.
         */
        MeResponse: {
            user: components["schemas"]["UserResponse"];
        };
        /**
         * MessageResponse
         * @description Generic message response (used for logout).
         */
        MessageResponse: {
            /** Message */
            message: string;
        };
        /**
         * SetupRequest
         * @description Body for POST /auth/setup — create the first admin user.
         */
        SetupRequest: {
            /** Email */
            email: string;
            /** Password */
            password: string;
        };
        /**
         * SetupStatusResponse
         * @description Response body for GET /auth/setup-status.
         */
        SetupStatusResponse: {
            /** Setup Required */
            setup_required: boolean;
        };
        /**
         * UserResponse
         * @description Public representation of a User (no password_hash).
         */
        UserResponse: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Email */
            email: string;
            /** Id */
            id: number;
            /** Is Active */
            is_active: boolean;
            /** Role */
            role: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login_api_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponse"];
                };
            };
        };
    };
    me_api_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeResponse"];
                };
            };
        };
    };
    setup_api_auth_setup_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetupRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    setup_status_api_auth_setup_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SetupStatusResponse"];
                };
            };
        };
    };
    list_categories_api_categories_get: {
        parameters: {
            query?: {
                /** @description Case-insensitive name substring filter. */
                q?: string | null;
                /** @description Filter by parent_id (omit to get all categories). */
                parent_id?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_category_api_categories_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CategoryCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_tree_api_categories_tree_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryTreeNode"][];
                };
            };
        };
    };
    get_category_api_categories__category_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                category_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_category_api_categories__category_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                category_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_category_api_categories__category_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                category_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CategoryUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_definitions_api_definitions_get: {
        parameters: {
            query?: {
                /** @description Case-insensitive name substring filter. */
                q?: string | null;
                /** @description Filter by category_id. */
                category_id?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DefinitionResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_definition_api_definitions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DefinitionCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DefinitionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_definition_api_definitions__definition_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                definition_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DefinitionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_definition_api_definitions__definition_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                definition_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_definition_api_definitions__definition_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                definition_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DefinitionUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DefinitionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    list_instances_api_instances_get: {
        parameters: {
            query?: {
                /** @description Case-insensitive substring match on serial, model_number, or manufacturer. */
                q?: string | null;
                /** @description Filter by definition_id. */
                definition_id?: number | null;
                /** @description Filter by location_id. */
                location_id?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InstanceResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_instance_api_instances_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InstanceCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InstanceResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_instance_api_instances__instance_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                instance_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InstanceResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_instance_api_instances__instance_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                instance_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_instance_api_instances__instance_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                instance_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InstanceUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InstanceResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_kinds_api_kinds_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KindResponse"][];
                };
            };
        };
    };
    list_locations_api_locations_get: {
        parameters: {
            query?: {
                /** @description Case-insensitive name substring filter. */
                q?: string | null;
                /** @description Filter by parent_id (pass 0 to get root locations is NOT supported; omit to get all). */
                parent_id?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LocationResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_location_api_locations_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LocationCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LocationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_tree_api_locations_tree_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LocationTreeNode"][];
                };
            };
        };
    };
    get_location_api_locations__location_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                location_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LocationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_location_api_locations__location_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                location_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_location_api_locations__location_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                location_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LocationUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LocationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
